#spring.application.name=JobApplication
#spring.datasource.url=jdbc:h2:mem:test
#spring.h2.console.enabled=true
#jwt.secret=mySecretKeyForLearningJwtAuthentication123456789
#jwt.expiration=86400000

spring.application.name=JobApplication

# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/jobportal
spring.datasource.username=postgres
spring.datasource.password=Rgraj@99
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT
jwt.secret=mySecretKeyForLearningJwtAuthentication123456789
jwt.expiration=86400000